import { initializeApp } from "https://www.gstatic.com/firebasejs/10.7.1/firebase-app.js";
import { getFirestore } from "https://www.gstatic.com/firebasejs/10.7.1/firebase-firestore.js";

// Firebase config injected at build time from secrets
// Ensure firebase-config.js is generated by your CI/CD pipeline
// and loaded in index.html before this module.
const app = initializeApp(window.firebaseConfig);

// Export Firestore instance for use in other modules
export const db = getFirestore(app);
